version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - server-a
    environment:
      - VITE_API_URL=http://localhost:3001

  server-a:
    build: ./server-a
    ports:
      - "3001:3001"
    depends_on:
      - db
      - server-b
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=animals_db

  server-b:
    build: ./server-b
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=adoptions_db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: animals_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
