version: "3.9"

services:
  server-a:
    build:
      context: ./server-a
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server-a:/app
    environment:
      - NODE_ENV=development

  server-b:
    build:
      context: ./server-b
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./server-b:/app
    environment:
      - NODE_ENV=development

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adoptiondb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
